### ISSUE TITLE
TODOs Tracker

### ISSUE THREAD

**Issue by PkuCuipy** [PkuCuipy/gpa-simulator#1]
- [x] Hello, Task List!
- [x] 导入界面的提示内容优化
- [x] 支持 100 分以彩虹色显示
- [x] 百分制课程分数相同时按名称排序、非百分制课程按 `P`, `EX`, `I`, `NP`, `F`, `W` 顺序排列, 相同时按名称排序
- [x] GPA 无法计算时从显示 `NaN` 改为显示 `-.---`
- [x] 添加新课程时的默认参数: 学期按照当前日期智能推荐、课名随机生成、学分和成绩随机生成
- [x] 修改成绩为非法值后, 回退到上一个合法值, 而非回退到最初的值
